java -jar yuicompressor-2.4.8.jar main.js -o min\main.min.js
java -jar yuicompressor-2.4.8.jar settings.js -o min\settings.min.js
java -jar yuicompressor-2.4.8.jar cases2.js -o min\cases2.min.js
java -jar yuicompressor-2.4.8.jar prices.js -o min\prices.min.js
java -jar yuicompressor-2.4.8.jar skinNames.js -o min\skinNames.min.js
java -jar yuicompressor-2.4.8.jar quality.js -o min\quality.min.js
java -jar yuicompressor-2.4.8.jar openCase.js -o min\openCase.min.js
java -jar yuicompressor-2.4.8.jar coinflip.js -o min\coinflip.min.js
java -jar yuicompressor-2.4.8.jar double.js -o min\double.min.js
java -jar yuicompressor-2.4.8.jar inventory.js -o min\inventory.min.js
java -jar yuicompressor-2.4.8.jar jackpotBots.js -o min\jackpotBots.min.js
java -jar yuicompressor-2.4.8.jar localization.js -o min\localization.min.js
java -jar yuicompressor-2.4.8.jar marketplace.js -o min\marketplace.min.js
java -jar yuicompressor-2.4.8.jar navigationMenu.js -o min\navigationMenu.min.js
java -jar yuicompressor-2.4.8.jar news.js -o min\news.min.js
java -jar yuicompressor-2.4.8.jar ranks.js -o min\ranks.min.js
java -jar yuicompressor-2.4.8.jar rps.js -o min\rps.min.js
java -jar yuicompressor-2.4.8.jar rulet.js -o min\rulet.min.js
PAUSE